@rootapi = http://localhost:8000/api/v1

###server test 
 GET http://localhost:8000

### Sign up 
POST {{rootapi}}/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "phoneNumber": "9876543210",
  "password": "securePassword123",
  "profilePicture": "https://example.com/profile.jpg",
  "role": "student"
}

### login
POST {{rootapi}}/auth/login
Content-Type: application/json

{
  "email" : "johndoe@example.com",
  "password": "securePassword123"
}